# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 5fa0adbc2e5fc6d1e2281f668719f74d912780df08689316075fd2d9b1c41d008b07e79a3c486bfcfbafb0f0a5f81cd1e0f92d3fa7c5a9df38da86116f6850f2

test:
  secret_key_base: 4fd96a377595ec4d2c138a147c89c9b15b491e6263c75ebee49b7753ec3ed037327a97a799df1feda94a044dc5f9573097eba871de5bddac109a98b3bc387fa1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
